apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas.agent.executor.us-central
  labels:
    app: executor
    project: carbon-aware-scheduler
    component: executor
    region: us-central
spec:
  replicas: 1
  selector:
    matchLabels:
      app: executor
      project: carbon-aware-scheduler
      component: executor
      region: us-central
  template:
    metadata:
      labels:
        app: executor
        project: carbon-aware-scheduler
        component: executor
        region: us-central
    spec:
      volumes:
      - name: secret-cas-serviceaccount-kube-config
        secret:
          secretName: cas-serviceaccount
      containers:
      - name: cas-agent-executor-us-central
        image: gitlab-registry.nrp-nautilus.io/c3lab/carbon-aware-scheduler/agent.executor:0.1
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cas-queue-config
          - secretRef:
              name: cas-master-database
        env:
          - name: REGION
            value: us-central
          - name: POSTGRES_HOST
            value: cas-master-database
        volumeMounts:
          - name: secret-cas-serviceaccount-kube-config
            readOnly: true
            mountPath: "/root/.kube/"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "1"
      imagePullSecrets:
        - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - "us-central"
