apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas.agent.executor.us-west
  labels:
    app: executor
    project: carbon-aware-scheduler
    component: executor
    region: us-west
spec:
  replicas: 1
  selector:
    matchLabels:
      app: executor
      project: carbon-aware-scheduler
      component: executor
      region: us-west
  template:
    metadata:
      labels:
        app: executor
        project: carbon-aware-scheduler
        component: executor
        region: us-west
    spec:
      containers:
      - name: cas-agent-executor-us-west
        image: gitlab-registry.nrp-nautilus.io/c3lab/carbon-aware-scheduler/agent.executor:0.1
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cas-queue-config
        env:
        - name: REGION
          value: us-west
        resources:
          limits:
            memory: 256Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: 500m
      imagePullSecrets:
        - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - "us-west"
