# Source: https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.3/examples/celery-rabbitmq/rabbitmq-controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas.rabbitmq.job-queue
  labels:
    app: job-queue
    project: carbon-aware-scheduler
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-queue
      project: carbon-aware-scheduler
      component: rabbitmq
  template:
    metadata:
      labels:
        app: job-queue
        project: carbon-aware-scheduler
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
