apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas.master.job-scheduler
  labels:
    app: job-scheduler
    project: carbon-aware-scheduler
    component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      project: carbon-aware-scheduler
      component: master
      app: job-scheduler
  template:
    metadata:
      labels:
        project: carbon-aware-scheduler
        component: master
        app: job-scheduler
    spec:
      initContainers:
      - name: init-job-queues
        image: gitlab-registry.nrp-nautilus.io/c3lab/common/rabbitmq-client:alpine
        envFrom:
          - configMapRef:
              name: cas-queue-config
        command: [ "sh", "-c" ]
        args:
          - |
            for region in ${REGIONS//:/ }; do
              /usr/bin/amqp-declare-queue --url=$BROKER_URL -q "$QUEUE_PERFIX.$region" -d
            done
      containers:
      - name: cas-master-job-scheduler
        image: gitlab-registry.nrp-nautilus.io/c3lab/carbon-aware-scheduler/master.job-scheduler:0.1
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cas-queue-config
        env:
        - name: CARBON_API_ENDPOINT
          value: cas-carbon-api
        ports:
          - containerPort: 8000
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: 500m
      imagePullSecrets:
        - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - "us-west"
                      - "us-central"
                      - "us-east"
