apiVersion: v1
kind: Pod
spec:
  # Secret setup: https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pod-with-ssh-keys
  volumes:
    - name: secret-vol-cephs3-rclone-config
      secret:
        secretName: cas-cephs3-rclone-conf
    - name: pvc-vol
      persistentVolumeClaim:
        claimName: VAR_pvc_name
  containers:
  - name: data-transfer-s3-pvc
    image: gitlab-registry.nrp-nautilus.io/c3lab/common/rclone:1.61.1
    # imagePullPolicy: Always
    stdin: true
    stdinOnce: true
    tty: true
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["sh", "-c"]
    args:
      - >
        cd "/pvc-vol" && sh
    volumeMounts:
      - name: secret-vol-cephs3-rclone-config
        readOnly: true
        mountPath: "/root/.config/rclone/"
      - name: pvc-vol
        mountPath: "/pvc-vol"
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - VAL_node_region
