apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cas-master-database
  labels:
    app: database
    project: carbon-aware-scheduler
    component: master
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
