apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
    project: carbon-aware-scheduler
    component: master
  name: cas-master-database
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: database
    project: carbon-aware-scheduler
    component: master
  type: ClusterIP
