apiVersion: batch/v1
kind: Job
metadata:
  name: VAR_job_name
  labels:
    job-uuid: VAR_job_uuid
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: VAR_container_name
        image: VAR_image
        # imagePullPolicy: Always
        resources:
          limits:
            memory: VAR_limit_ram
            cpu: VAR_limit_cpu
          requests:
            memory: VAR_request_ram
            cpu: VAR_request_cpu
        command: []
        args: []
        volumeMounts: []
          # - name: pvc-vol
          #   mountPath: "/pvc-vol"
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      volumes: []
        # - name: VAR_vol_name
        #   persistentVolumeClaim:
        #     claimName: VAR_pvc_name
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - VAL_node_region